Close cursor in the cursor adapter onDestroyView, per logcat:
Finalizing a Cursor that has not been deactivated or closed. database = /data/data/com.kennyc.open.imgur/databases/open_imgur.db, table = null, query = SELECT * FROM subreddits WHERE name LIKE '%android%'
    android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

I saw this log when I was on the subreddit screen and was rotating. Checked to see if there were other places where cursoradapter was used and found none, so here is the only issue.